### ISSUE TITLE
all: use shfmt to format shell scripts

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-common#102]
Carlos suggested setting up [shfmt](https://github.com/mvdan/sh) to automatically format our .sh files

From their doc page:
> to get the formatting appropriate for Google's Style guide, use `shfmt -i 2 -ci`

**Comment by mr-salty** [comment]
(all: means this applies to all repos... common seems like the best place to file bugs like that?)

**Comment by devjgm** [comment]
Done https://github.com/googleapis/google-cloud-cpp/pull/3831
