### ISSUE TITLE
vcpkg package doesn't provide google_cloud_cpp_testing

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp-common#109]

**Comment by coryan** [comment]
I have been thinking about this some more, and I think the answer is we do *not* want the vcpkg packages to compile with testing enabled, at least not by default. It just makes the experience worse for the users, as the builds take longer.

The downside is that *our* builds cannot depend on the vcpkg packages, at least not directly. We should enable testing as an optional feature:

https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#feature-paragraphs

And then our builds can turn on that feature.

**Comment by coryan** [comment]
See microsoft/vcpkg#9097

**Comment by coryan** [comment]
This is now fixed.
