### ISSUE TITLE
Replace google::cloud::optional<> with absl::optional<>

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#116]
Assuming we merge googleapis/google-cloud-cpp#685.  The `google::cloud::optional<T>` should be replaced by `absl::optional<T>` when we start using Abseil again, or with `std::optional<T>` when we only support C++17 and higher.

**Comment by devjgm** [comment]
Closing this because we have no specific Abseil plans at this point, and once we do, replacing optional will be a banner item that we won't forget. No need to drag this issue along forever.
