### ISSUE TITLE
Determine and document `grpc_utils::CompletionQueue` shutdown semantics

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-common#129]
We need to determine and document a safe way to shut down and destroy a `grpc_utils::CompletionQueue`.

#127 made some changes in this area but I'm still having difficulty with the case where I have a periodic worker that reschedules itself - I have written the test below which crashes with `assertion failed: grpc_cq_begin_op(cq_, this)`.

[grpc#8610](https://github.com/grpc/grpc/issues/8610) discusses the proper shutdown procedure for the underlying completion queue:

* Once you call cq->shutdown on a completion queue, you can no longer queue any more events on that queue. You will get an assertion failure if you do so.
* You must keep calling cq->Next() or cq->AsyncNext() on that queue to drain all the pending events. Once all the events are drained, cq->Next() will start returning false (or cq->AsyncNext() will return NextStatus::SHUTDOWN).
* This is when it is safe to delete/destroy your completion queue object

So, essentially the responsibility for ensuring no more events are enqueued after shutdown is pushed up to the user, do we want to keep the same semantics for `grpc_utils::CompletionQueue`?  If so, then I propose removing the member `shutdown_` from that class - the caller will need to track that state itself. 

Somewhat related, I believe [`if (shutdown_ && pending_ops_.empty()) break;`](https://github.com/googleapis/google-cloud-cpp-common/blob/672072a7724cb55d00f073be25ab55cdf594dddf/google/cloud/grpc_utils/internal/completion_queue_impl.cc#L49) is unnecessary - that condition is exactly the same as `cq_.AsyncNext()` returning `SHUTDOWN`.  If I comment out that line all the tests still pass, and I confirmed that in all cases, when we go back to the top of the `for()` loop it immediately returns `SHUTDOWN` and exits the loop.

```
// Make sure we shutdown cleanly even when events are still in the queue.
namespace {
void RunAndReschedule(CompletionQueue& cq) {
  cq.MakeRelativeTimer(std::chrono::seconds(1))
      .then([&cq](future<std::chrono::system_clock::time_point>) {
        RunAndReschedule(cq);
      });
}
}  // namespace
TEST(CompletionQueueTest, ShutdownWithEventsInQueue) {
  CompletionQueue cq;
  std::thread t([&cq] { cq.Run(); });
  RunAndReschedule(cq);
  cq.Shutdown();
  t.join();
}

**Comment by mr-salty** [comment]
Another related issue is what happens to events in the queue when `Shutdown` happens.  Per [grpc#8610](https://github.com/grpc/grpc/issues/8610), after `Shutdown`, `AsyncNext` will start setting `ok` to false, which is described as a "bug in grpc" [here](https://github.com/googleapis/google-cloud-cpp-common/blob/672072a7724cb55d00f073be25ab55cdf594dddf/google/cloud/grpc_utils/internal/completion_queue_impl.h#L108-L110); I don't believe that is the case. In the tests, we do see times that `ok == false` (I added additional logging), but we don't see it because we only use timers and they [ignore that parameter](https://github.com/googleapis/google-cloud-cpp-common/blob/672072a7724cb55d00f073be25ab55cdf594dddf/google/cloud/grpc_utils/completion_queue.cc#L64).

**Comment by mr-salty** [comment]
My third question is about the proper use of `CancelAll()`.  Should callers always call that prior to calling `Shutdown` (and only at that time)? If so, `Shutdown()` should just do it automatically and we can remove the call.

What are the consequences of *not* calling `CancelAll`?  IIUC it means that any items still in the queue will complete with a non-ok status.  So, if we handled `!ok` in [`AsyncUnaryRpcFuture::Notify()`](https://github.com/googleapis/google-cloud-cpp-common/blob/672072a7724cb55d00f073be25ab55cdf594dddf/google/cloud/grpc_utils/internal/completion_queue_impl.h#L107) (perhaps by calling `Cancel()`), could we eliminate `CancelAll()` entirely?

**Comment by coryan** [comment]
I have a proposal, the `google::cloud::CompletionQueue` should be hard to use wrong, IMO this means that it should (as much as possible) enforce the pre and post-conditions required by those `grpc::CompletionQueue` assertions. Consequently we should make the following changes:

- After one calls `g::c::CompletionQueue::Shutdown` these things happen:
  - `g::c::CompletionQueue::Run` continues to run until all pending operations have been removed.
  - `g::c::CompletionQueue` should stop accepting any new operations.
  - trying to add `g::c::CompletionQueue` that is shutting down will immediately fail the operation with `StatusOr` having `kCancelled` status.
  - this requires changing the API for timers, they need to return a `g::c::future<StatusOr<...::time_point>>`.

I can make these changes, but I think we first need to improve the code coverage in the `-common` unit tests (a lot of these functions are tested indirectly in `-cpp`).

To answer the question around `CancelAll()`: I think we should let those operations cancel by whatever mechanism `grpc::CompletionQueue` uses. No need to duplicate their work / approach.

Thoughts?

**Comment by mr-salty** [comment]
yeah, I agree with the general principle.

I believe `Run` always draining the queue is already fixed.

I have a PR in progress to propagate `ok` to the timers, and another to add an API for recurring timers so callers generally won't have to care.

Once that is done we can make the change to stop accepting new operations after shutdown - either one of us can do that.

I didn't grok what you were saying about about `CancelAll` though - it doesn't look like the grpc one has any concept of that so we have to do something ourself?

**Comment by mr-salty** [comment]
while writing tests for `ok` propagation, I discovered that any timers that have not been Cancelled will block `Shutdown` until the timer expires, and the timer event we get from the CQ in that case has `ok == true` (which makes sense, since it ran to completion).

So, if the caller calls `CancelAll(); Shutdown();` then its timers will get the `CANCELLED` status and can use that as a cue not to do any work, or reschedule themselves.

If the caller opts *not* to call `CancelAll` the timers will have no indication that `Shutdown` has been called.  This will not be an issue if we also implement the change to have any new operations queued immediately fail with `kCancelled`, so I'm inclined to do both of those things in one PR.

I still wonder if `grpc_utils::CompletionQueue` should automatically `CancelAll()` in `Shutdown()` which would also avoid the issue. I think Carlos' argument against that is that users may want to wait for RPCs to complete, but does that also apply to timers? Could we auto-cancel timers and not RPCs, and make the user call `CancelAll()` (or `CancelAllRpcs()`?) if they don't want to wait for RPCs?

One case I'm thinking of is, in the `SessionPool` we might have a timer that fires in 55 minutes (I'm not planning to actually implement it that way, but it's an option), and it's hard to imagine wanting to wait for that to finish. There is no way to force a `grpc::Alarm` to finish aside from Canceling it.

**Comment by mr-salty** [comment]
> I didn't grok what you were saying about about `CancelAll` though - it doesn't look like the grpc one has any concept of that so we have to do something ourself?

BTW I think I get this now, you're talking about i.e. `Alarm::Cancel` or `ClientContext::TryCancel()`, etc?

**Comment by coryan** [comment]
> 
> BTW I think I get this now, you're talking about i.e. `Alarm::Cancel` or `ClientContext::TryCancel()`, etc?

What I meant, and this is kind of vague and not very principled: we should not do "too much magic". In this case `g::c::CompletionQueue` should not magically cancel things for you, or it should behave just like `grpc::CompletionQueue` in this respect. However, offering a helper like `CancelAll()` seems fine to me.

As I said, it is sort of a vague guideline of "not do too much magic", somehow calling `CancelAll` felt like too much magic when I introduced it to be called implicitly, but maybe I am wrong.

**Comment by mr-salty** [comment]
I believe with #138 this is now fixed.

(PS: ugh, I never realized when I rebase my other branches and `push -f`, the commits show up (again) in the bug... yet #138 which I just merged shows up as "4 days ago" when I opened it... that's confusing.)
