### ISSUE TITLE
release google-cloud-cpp-common when #129 is resolved

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-common#130]
https://github.com/googleapis/google-cloud-cpp-spanner/issues/1171 (and 1172) will (*) require a version of the `CompletionQueue` with #129 fixed, so we'll need to re-release `common` (a point release) to be able to use it in `spanner`.

(*) is because I realized I _may_ be able to just work around the current `CompletionQueue` behavior in `SessionPool` without requiring a new release.

**Comment by mr-salty** [comment]
Well, there's supposed to be a release next week so no point doing a point release.

I'll reassign it to @devbww just to ensure commits up to #138 are included in the release - we may not really need a bug for that so feel free to close it.

**Comment by devbww** [comment]
https://github.com/googleapis/google-cloud-cpp-common/releases/tag/v0.18.0 is done.
