### ISSUE TITLE
CI builds are slow due to long Docker image build times

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-common#137]
I've noticed a number of CI builds taking an abnormally long time to run... usual had been ~20 minutes but occasionally builds are taking almost an hour to complete.

I looked at logs from some of these and the bulk of the time (even in "normal" ~20 minute builds) appears to be building a Docker image.  These should be cached, so perhaps the cache is misconfigured.

[example 1](https://source.cloud.google.com/results/invocations/2406779a-54b3-4a46-b9a1-e198db684e2f/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp-common%2Fmaster%2Fdocker%2Fninja-presubmit/log) - 50m21s overall, 47m36s spent here:

```
Creating Docker image with all the development tools Thu Jan 23 12:57:42 PST 2020.
Logging to cmake-out/ci-ubuntu-install-18.04-ninja/create-build-docker-image.log
================================================================
Detecting the branch name Thu Jan 23 13:45:18 PST 2020.
```

[example 2](https://source.cloud.google.com/results/invocations/5284f571-23d2-4d54-ab64-e058fce99eba/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp-common%2Fmaster%2Fdocker%2Fcheck-api-presubmit/log) - 50m45s overall, 47m39s spent here:

```
Creating Docker image with all the development tools Mon Jan 27 10:07:32 PST 2020.
Logging to cmake-out/ci-ubuntu-install-18.04-check-api/create-build-docker-image.log
================================================================
Detecting the branch name Mon Jan 27 10:55:11 PST 2020.
```

[example 3](https://source.cloud.google.com/results/invocations/68c7223b-51ed-456d-bb07-61cedd958455/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp-common%2Fmaster%2Fdocker%2Fninja-presubmit/log) - 21m01s overall, 18m23s here:

```
Creating Docker image with all the development tools Thu Jan 23 13:52:07 PST 2020.
Logging to cmake-out/ci-ubuntu-install-18.04-ninja/create-build-docker-image.log
================================================================
Detecting the branch name Thu Jan 23 14:10:30 PST 2020.
```

**Comment by coryan** [comment]
I think the `docker build` step is timing out (the timeout is 3600s) and therefore: (1) the build falls back to the old image from the cache, and (2) the cache is not refreshed because there is no new image.

I am pushing a new image to the cache as a workaround.

**Comment by coryan** [comment]
For what it is worth, this is a build that failed, with more debugging information:

https://source.cloud.google.com/results/invocations/e382d7cc-19c2-47d7-9538-d90a5d06f0bb

**Comment by coryan** [comment]
Also, it seems the crashes are because `NCPU` is not set here:

https://github.com/googleapis/google-cloud-cpp-common/blob/a1a3821651fa39254bc5d020e40fb0357fe0ec20/ci/kokoro/docker/Dockerfile.ubuntu-install#L88

The value discarded after the `FROM ` line here:

https://github.com/googleapis/google-cloud-cpp-common/blob/a1a3821651fa39254bc5d020e40fb0357fe0ec20/ci/kokoro/docker/Dockerfile.ubuntu-install#L15-L18
