### ISSUE TITLE
Move GOOGLE_CLOUD_CPP_ENABLE_CLOG envvar to log.{h,cc}

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-common#177]
Since `GOOGLE_CLOUD_CPP_ENABLE_CLOG` affects the global `google::cloud::LogSink::EnableStdClog()`, it seems like that env var should be used and documented in the `log.{h,cc}` library. I think this will be the natural place where users will look to learn how to configure logging.

Note that today, this env var is set in other libraries, such as spanner:
https://github.com/googleapis/google-cloud-cpp-spanner/blob/44d687f3331d6a1bc57e9314526efda4768a1692/google/cloud/spanner/connection_options.cc#L60-L63

Note that the env var is named generically (not for spanner) and it affects the global log sink.

**Comment by devbww** [comment]
It looks like this was addressed in googleapis/google-cloud-cpp-spanner#1279.

**Comment by coryan** [comment]
I agree, closing.
