### ISSUE TITLE
Add `test_util::ScopedEnv` class

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp-common#178]
I think we probably want a class like the following:

```cc
class ScopedEnv {
 public:
  ScopedEnv(std::string name, google::cloud::optional<std::string> value)
      : name_(std::move(name)) {
    orig_value_ = google::cloud::internal::GetEnv(name.c_str());
    google::cloud::internal::SetEnv(name_.c_str(), std::move(value));
  }
  ~ScopedEnv() {
    google::cloud::internal::SetEnv(name_.c_str(), std::move(orig_value_));
  }

 private:
  std::string name_;
  google::cloud::optional<std::string> orig_value_;
};
```

I think it could probably replace the https://github.com/googleapis/google-cloud-cpp-common/blob/master/google/cloud/testing_util/environment_variable_restore.h class, as this `ScopedEnv` could be a fixture member and its c'tor and d'tor would be called automatically avoiding the need for the SetUp and TearDown calls.

Steps:

- [ ] Add the new `ScopedEnv` class to this `-common` repo.
- [ ] Wait for a release of `-common`.
- [ ] Update our other repos to use the new `-common`, and replace their uses of `EnvironmentVariableRestore` with `ScopedEnv`.
- [ ] Delete the `EnvironmentVariableRestore` class in `-common`.

Of course, all this assumes that our `google::cloud::test_util` stuff is not part of our public API. I

**Comment by devbww** [comment]
Apart from the loss of the public `SetUp()` and `TearDown()` functions, which I have previously questioned the need for, this looks like just a name change (`EnvironmentVariableRestore` to `ScopedEnv`), which I'm mostly ambivalent on.

If we're going to design anything, what I might prefer is an `EnvironmentRestorer` object, with a `SetEnv()` member function[*], and a destructor that undoes all of its `SetEnv()`s.

[*] And an `UnsetEnv()` if you don't want to involve `optional<>`.

**Comment by coryan** [comment]
Maybe we can just remove the `SetUp()` and `TearDown()` functions?  I think I just cargo culted those in the unit tests that use the `EnvironmentVariableRestore` class as part of a fixture :disappointed: The fixture will call the constructor and destructor anyway. Just a thought.

**Comment by devjgm** [comment]
This was my mistake. I read the code too fast, and I missed that `EnvironmentVariableRestore` was already restoring the variable in its d'tor. I thought it *required* SetUp and TearDown. I misread.

Given that, `EnvironmentVariableRestore` works fine for my current needs.

I think we could probably remove the SetUp and TearDown methods, but that's certainly not urgent.

Closing this.
