### ISSUE TITLE
Audit ci/kokoro/docker image caching in all the repos

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#197]
We want all the builds to cache their docker images for `ci/kokoro/docker/*`, make sure the `build.sh` looks like the one from `-spanner`:

- [ ] `-common`
- [ ] `-cpp`
- [ ] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
Done in -cpp. https://github.com/googleapis/google-cloud-cpp/issues/3612
