### ISSUE TITLE
Audit ci/kokoro/install image caching in all the repos

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#198]
We want all the builds to cache their docker images for `ci/kokoro/install/*`, make sure the `build.sh` looks like the one from `-spanner`:

- [ ] `-common`
- [ ] `-cpp`
- [ ] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
Our monorepo, `-cpp` is already caching docker images. So done. https://github.com/googleapis/google-cloud-cpp/issues/3612
