### ISSUE TITLE
Caching artifacts for Bazel builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#202]
The Bazel builds are kind of slow because they rebuild everything (including the dependencies) from scratch each time. We should consider saving the `$HOME/.cache/bazel` to GCS and restoring it before each build.

We do something similar for Windows, where we download the build artifacts:

https://github.com/googleapis/google-cloud-cpp-common/blob/00175c520d4c32f8cac115ea11c84ee97d5bbdaa/ci/kokoro/windows/build-cmake-dependencies.ps1#L46-L62

we use them as a cache if available, and then upload them again:

https://github.com/googleapis/google-cloud-cpp-common/blob/00175c520d4c32f8cac115ea11c84ee97d5bbdaa/ci/kokoro/windows/build-cmake-dependencies.ps1#L105-L119

We would need to ensure each build gets a different object on GCS.  We also need to make sure the Docker container running our build gets these in the right `$HOME`, but it might work.

Testing this on `-common` before moving to other builds might be a good idea.

We *may* be able to do something similar for CMake with ccache.

**Comment by coryan** [comment]
/cc: @mr-salty because you were interested in this, I won't be working on it

**Comment by devjgm** [comment]
Done as part of https://github.com/googleapis/google-cloud-cpp/milestone/14
