### ISSUE TITLE
Reduce size of -install docker images for CI builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#203]
For the CI builds we use `-install` Dockerfiles that pre-compile the dependencies for the project. These are typically found in the `ci/kokoro/docker/` directory. These images are fairly large (I just clocked one at 2GiB), and could be smaller if we:

-# Removed the intermediate build artifacts for the dependencies (all those `.o` files) after installing, **or**
-# Used a stage and copy copied the `/usr/local` directory to the final stage, but that breaks caching to do quick rebuilds of the image in a PR.

**Comment by devjgm** [comment]
Looks like this was done by googleapis/google-cloud-cpp#3458
