### ISSUE TITLE
Use the -spanner style for README.md and INSTALL.md

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#207]
We made a number of changes in `-spanner` to improve the `README.md` and `INSTALL.md` file (including changing that to `doc/packaging.md`) we should do this across the repositories:

- [ ] `-common`
- [ ] `-cpp`
- [x] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
Done in our monorepo in https://github.com/googleapis/google-cloud-cpp/pull/3724
