### ISSUE TITLE
Use the same distribution for all check-api builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#213]
Some of our projects compare the API against a baseline committed into the repository (in ci/test-api).  We should use the same distribution and tooling for all these builds, probably Fedora:31.

- [ ] `-common`
- [ ] `-cpp` **also** rename from `check-abi` to `check-api`
- [ ] `-spanner`

**Comment by devjgm** [comment]
Obsolete due to our move to a monorepo. https://github.com/googleapis/google-cloud-cpp/issues/3612
