### ISSUE TITLE
Parallelize code coverage builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#229]
The code coverage builds are fairly slow because they serialize the tests. To parallelize them, we need a different `GCOV_PREFIX` for each program:

https://gcc.gnu.org/onlinedocs/gcc/Cross-profiling.html

- [ ] `-common`
- [ ] `-cpp`
- [ ] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
Not going to do this. See https://github.com/googleapis/google-cloud-cpp/issues/3530
