### ISSUE TITLE
Uniform defaults for ci/kokoro/docker/build.sh

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#236]
Different repositories have different defaults for the "in docker" script, the Docker image, etc. We should make all of the repositories uniform.  Probably the best is to have **no default** and have each build configure the parameters it needs explicitly.

- [ ] `-common`
- [ ] `-cpp`
- [ ] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
Obsolete due to our move to a monorepo https://github.com/googleapis/google-cloud-cpp/issues/3612
