### ISSUE TITLE
Uniform integration config files for ci/kokoro/*/build.{sh,ps1}

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#237]
Different repositories have different names for the configuration files used in the integration tests, some files include the name of the repository (which is useful when testing multiple repositories in your workstation), some files are stored in a per-repository folder in our GCS bucket, some do not. We should make them all look the same, and then read the name of these files from `ci/etc/` or something.

- [ ] `-common`
- [ ] `-cpp`
- [ ] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
Obsolete due to our move to a monorepo: https://github.com/googleapis/google-cloud-cpp/issues/3612
