### ISSUE TITLE
Load vcpkg dependencies from `ci/etc`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#238]
The build scripts (for Windows) have a hard-coded list of dependencies, but different projects need different ones.  For example, only `-spanner` depends on `benchmark`, and only `-cpp` depends on `libcurl` and `crc32c`. We should load this list from some configuration file in `ci/etc`, so the scripts are actually identical.

- [ ] `-common`
- [ ] `-cpp`
- [ ] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
Moving to a monorepo, we only have `-cpp`, so we don't need to worry about configuring this across repos.
