### ISSUE TITLE
Use UTC timestamps in all the ci/kokoro/* scripts.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#239]
Usually the Kokoro VMs are running on Google Standard Time, but the containers are running in UTC, which makes comparing timestamps annoying (not hard, just annoying).

- [ ] `-common`
- [ ] `-cpp`
- [ ] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
Done in https://github.com/googleapis/google-cloud-cpp/pull/3704 for -cpp, which will be our only repo.
