### ISSUE TITLE
Audit bazelrc file across all repositories

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#246]
Make sure they all look the same, probably `-spanner` or `-pubsub` are the exemplars in this case:

- [ ] `-common`
- [ ] `-cpp`
- [ ] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
Done. `-cpp` has the canonical .bazelrc file now.
