### ISSUE TITLE
Do not update vcpkg cache in pull request builds.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#249]
This dirties the cache when testing changes to the vcpkg dependencies, and slows down other builds. Likewise, it slows down the build when nothing has changed.

- [ ] `-common`
- [x] `-cpp`
- [ ] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

**Comment by devjgm** [comment]
This was done in `-cpp` in https://github.com/googleapis/google-cloud-cpp/pull/3513, and since we're moving to that as our only repo, it doesn't make sense to do in -common or -spanner.

So I'm calling this done.
