### ISSUE TITLE
Migrate check-markdown.sh from spanner to the all repositories

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-common#260]
In `-spanner` @devjgm just wrote a script to verify the generated `.md` files are up to date on each PR. I think we want the same for the other repositories (that have them):

- [ ] `-common`
- [x] `-cpp`
- [x] `-spanner`
- [ ] `-pubsub`
- [ ] `-bigquery`

See googleapis/google-cloud-cpp-spanner#1421 for more details.

**Comment by devjgm** [comment]
Done. It exists in `-cpp`, and that's our only other repo now.
