### ISSUE TITLE
findutils (required by bazel) is not installed on Fedora

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-common#86]
I noticed this error in a [test log](https://source.cloud.google.com/results/invocations/6ccd4e09-1fa4-4500-ab52-b377b647fa00/targets/cloud-cpp%2Fspanner%2Fdocker%2Fmsan-presubmit/log):

`external/bazel_tools/tools/test/test-setup.sh: line 323: find: command not found`

Per Carlos, we need to include `findutils` in the `Dockerfile.fedora*` files

**Comment by devjgm** [comment]
I think this has been fixed. Our fedora builds do install findutils now, and nobody has seen this error AFAIK.
